name: ktlint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run ktlint
        run: ./gradlew ktlintCheck 